// Generated by IcedCoffeeScript 1.7.1-b
(function() {
  var Enum;

  Enum = require('iced-utils')["enum"].Enum;

  exports.C = {
    encodings: new Enum({
      json: 1,
      msgpack: 2,
      msgpack64: 3
    }),
    version: {
      V1: 1
    }
  };

}).call(this);
