// Generated by IcedCoffeeScript 1.7.1-b
(function() {
  var decode, decode_json_obj, encode, mime_types, mime_types_r, _ref, _ref1;

  encode = require('./encode').encode;

  _ref = require('./decode'), decode = _ref.decode, decode_json_obj = _ref.decode_json_obj;

  _ref1 = require('./mime'), mime_types = _ref1.mime_types, mime_types_r = _ref1.mime_types_r;

  exports.to_content_type_and_body = function(_arg) {
    var body, ct, encoding, err, obj;
    encoding = _arg.encoding, obj = _arg.obj;
    err = ct = body = null;
    encoding || (encoding = 'json');
    if (encoding === 'json' || encoding === 'msgpack' || encoding === 'msgpack64') {
      body = encode({
        obj: obj,
        encoding: encoding
      });
      ct = mime_types[encoding];
    } else {
      err = new Error("unknown encoding: " + encoding);
    }
    return [err, ct, body];
  };

  exports.from_content_type_and_body = function(_arg) {
    var body, content_type, encoding, err, ret, _ref2;
    content_type = _arg.content_type, body = _arg.body;
    ret = err = null;
    encoding = mime_types_r[content_type];
    if (encoding != null) {
      _ref2 = decode({
        buf: body,
        encoding: encoding
      }), err = _ref2[0], ret = _ref2[1];
    } else {
      ret = body;
    }
    return [err, ret];
  };

}).call(this);
